# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v1
    - name: Pre-install
      run: |
        brew update
        brew install llvm@18
        # Important: add empty string
        echo "" >> /Users/runner/.bash_profile
        echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> /Users/runner/.bash_profile
        echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"' >> /Users/runner/.bash_profile
        echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"' >> /Users/runner/.bash_profile
        source /Users/runner/.bash_profile
        clang --version
        swift --version
#        swift utils/make-pkg-config.swift

    - name: Build
      run: swift build -v
#    - name: Run tests
#      run: swift test -v

